config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root to: 'visitors#new'
end

app/models/contact.rb
class Contact
	include ActiveModel::Model
	attr_accessor :name, :string
	attr_accessor :email, :string
	attr_accessor :content, :string

	validates_presence_of :name
	validates_presence_of :email	
	validates_presence_of :content
	validates_format_of :email,
		:with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
	validates_length_of :content, :maximum => 500

	def update_spreadsheet
		connection = GoogleDrive.login(Rails.application.secrets.email_provider_username, Rails.application.secrets.email_provider_password)
		ss = connection.create_spreadsheet('Learn-Rails-Example')
		if ss.nil?
			ss = connection.create_spreadsheet('Learn-Rails-Example')
		end

		ws=ss.worksheets[0]
		last_row = 1 + ws.num_rows
		ws[last_row, 1] = Time.new
		ws[last_row, 2] = self.name
	    ws[last_row, 3] = self.email
	    ws[last_row, 4] = self.content
	    ws.save
	end

end

app/models/visitor.rb
class Visitor
	include ActiveModel::Model
	attr_accessor :email, :string
	validates_presence_of :email
	validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

	def subscribe
		mailchimp = Gibbon::API.new(Rails.application.secrets.mailchimp_api_key)
		result = mailchimp.lists.subscribe({
		  :id => Rails.application.secrets.mailchimp_list_id,
		  :email => {:email => self.email},
		  :double_optin => false,
		  :update_existing => true,
		  :send_welcome => true
		})
		Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
	end
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(secure_params)
		if @contact.valid?
			@contact.update_spreadsheet
			UserMailer.contact_email(@contact).deliver
			flash[:notice] = "Message sent from #{@contact.name}."
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def secure_params
		params.require(:contact).permit(:name, :email, :content)
	end


end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

def new
	@visitor = Visitor.new
end

def create
	@visitor = Visitor.new(secure_params)
	if @visitor.valid?
		@visitor.subscribe
		flash[:notice] = "Signed up #{@visitor.email}."
		redirect_to root_path
	else
		render :new
	end
end

private


def secure_params
	params.require(:visitor).permit(:email)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
<div class="form">
	<%= simple_form_for @contact do |form| %>
	  <%= form.error_notification %>
	  <%= form.input :name, autofocus: true %>
	  <%= form.input :email %>
	  <%= form.input :content, as: :text %>
	  <%= form.button :submit, 'Submit', class: 'submit' %>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Landing Page', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer class="row">
      <section class="small-4 columns">
        Copyright 2015
      </section>  
      <section class="small-8 columns">
        All rights reserved.
      </section> 
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3> About Foobar Kadigan</h3>
<p> He was born in Waikikamukau, New Zealand. He left New Zealand for England, excelled
at the University of Mopery, and served in the Royal Loamshire Regiment. While in
service, he invented the kanuten valve used in the processing of unobtainium for
industrial use. With a partner, Granda Fairbook, he founded Acme Manufacturing, later
acquired by the Advent Corporation, to develop his discovery for use in the
Turboencabulator. Mr. Kadigan is now retired and lives in Middlehampton with a favorite
cat, where he raises Griadium frieda and collects metasyntactic variables. </p>
<p>His favorite quote is:</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil placeat inventore magnam laboriosam quo totam voluptatibus culpa laborum. Provident delectus reiciendis incidunt debitis totam esse vero nesciunt a? Aspernatur, fugit.</p>

app/views/visitors/new.html.erb
<% content_for :title do %>Foobar Kadigan<% end %>
<% content_for :description do %>Website of Foobar Kadigan<% end %>
<section>
	<img src="http://lorempixel.com/1170/600/cats/1" alt="">
</section>
<section>
	<div class="column">
		<h2>Stay in touch.</h2>
	</div>
	<div class="form-centered">
	  <%=simple_form_for @visitor do |f| %>
	  <%= f.error_notification %>
	  <%= f.input :email, lable: false, :placeholder => 'Your email address...' %>
	  <br/>
	  <%= f.button :submit, "Sign up for the newsletter", :class => "submit" %>
	  <% end %>
	</div>
</section>